services:
  postgres-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: pdf_summariser_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pdf-summariser-network

  localstack:
    image: localstack/localstack:3.0
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SKIP_INFRA_DOWNLOADS=1
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pdf-summariser-network

  pdf-summariser-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres-db
      - localstack
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/usr/src/pdf_summariser
    networks:
      - pdf-summariser-network

  pdf-summariser-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - pdf-summariser-backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/pdf_summariser
    networks:
      - pdf-summariser-network

networks:
  pdf-summariser-network:

volumes:
  pg-data:
  localstack-data:
