default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements/local.in
        args: [src/requirements/local.in]
        files: ^requirements/(base|local)\.(txt|in)$
        additional_dependencies: ["pip==24.2"] # https://github.com/jazzband/pip-tools/issues/2131
      - id: pip-compile
        name: pip-compile requirements/prod.in
        args: [src/requirements/prod.in]
        files: ^requirements/(base|prod)\.(txt|in)$
        additional_dependencies: ["pip==24.2"] # https://github.com/jazzband/pip-tools/issues/2131
      - id: pip-compile
        name: pip-compile requirements/test.in
        args: [ src/requirements/test.in ]
        files: ^requirements/(base|test)\.(txt|in)$
        additional_dependencies: ["pip==24.2"] # https://github.com/jazzband/pip-tools/issues/2131

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        files: '^.*\.(py|in)$'
      - id: debug-statements
