[pytest]

testpaths=tests
python_files=test_*.py
addopts = -s --nomigrations

DJANGO_SETTINGS_MODULE=settings.test

# https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#auto-mode
asyncio_mode = auto
